name: bmi_calculator
description: A new Flutter project.

version: 1.0.5+9

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.4.0
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.1.1
  share_plus: ^7.0.2
  launch_review: ^3.0.1
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  cupertino_icons: ^1.0.5
  provider: ^6.0.5

  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_analytics: ^10.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "Assets/Images/ic_launcher.png" 
  android: true
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: Assets/fonts/GoogleSansRegular.ttf
